version: '3.8'

services:
  # 自动化测试平台应用 (3副本高可用)
  app:
    image: automation-platform:latest
    ports:
      - "3000:3000"

    # Swarm 部署配置
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

    # 环境变量配置（非敏感信息）
    environment:
      - NODE_ENV=production
      - PORT=3000
      # 数据库配置（非敏感）
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      # Jenkins 配置（非敏感）
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_JOB_NAME=${JENKINS_JOB_NAME}
      - JENKINS_JOB_API=${JENKINS_JOB_API}
      - JENKINS_JOB_UI=${JENKINS_JOB_UI}
      - JENKINS_JOB_PERF=${JENKINS_JOB_PERF}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - API_CALLBACK_URL=${API_CALLBACK_URL}
      - JENKINS_ALLOWED_IPS=${JENKINS_ALLOWED_IPS}
      - JENKINS_DEBUG_IP=${JENKINS_DEBUG_IP}

      # Docker Secrets 文件路径（敏感信息）
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - JENKINS_TOKEN_FILE=/run/secrets/jenkins_token
      - JENKINS_API_KEY_FILE=/run/secrets/jenkins_api_key
      - JENKINS_JWT_SECRET_FILE=/run/secrets/jenkins_jwt_secret
      - JENKINS_SIGNATURE_SECRET_FILE=/run/secrets/jenkins_signature_secret
      - JWT_SECRET_FILE=/run/secrets/jwt_secret

    # Docker Secrets 挂载
    secrets:
      - db_password
      - jenkins_token
      - jenkins_api_key
      - jenkins_jwt_secret
      - jenkins_signature_secret
      - jwt_secret

    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # 网络配置
    networks:
      - automation-network

    # 日志配置
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx 反向代理和负载均衡
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0644

    networks:
      - automation-network

    depends_on:
      - app

    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Redis 缓存服务
  redis:
    image: redis:7-alpine

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

    command: redis-server --appendonly yes --maxmemory 200mb --maxmemory-policy allkeys-lru

    volumes:
      - redis-data:/data

    networks:
      - automation-network

    # 健康检查
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

# Docker Secrets 定义 (外部创建)
secrets:
  db_password:
    external: true
  jenkins_token:
    external: true
  jenkins_api_key:
    external: true
  jenkins_jwt_secret:
    external: true
  jenkins_signature_secret:
    external: true
  jwt_secret:
    external: true

# 配置文件
configs:
  nginx_config:
    file: ./configs/nginx.swarm.conf

# 持久化存储
volumes:
  redis-data:
    driver: local

# 网络配置
networks:
  automation-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.10.0/24